name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os:
          - distro: debian
            codename: bullseye
          - distro: debian
            codename: bookworm
          - distro: debian
            codename: testing

          - distro: ubuntu
            codename: focal
          - distro: ubuntu
            codename: jammy
          - distro: ubuntu
            codename: mantic
          - distro: ubuntu
            codename: noble
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.os.distro }} ${{ matrix.os.codename }}
        uses: docker/build-push-action@v5
        with:
          context: "{{ defaultContext }}:${{ matrix.os.distro }}/${{ matrix.os.codename }}"

  shellcheck:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@cd81f4475ab741e097ec0fe73b692f3e49d66b8c
        with:
          scandir: "."
